package com.workflow.WorkFlowDEMO.api.utils;

import java.security.SecureRandom;

public class RandomPasswordGenerator {

    //Letters and numbers set
    private static final String CHARACTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    // Special characters set
    private static final String SPECIAL_CHARACTERS = "!@#$%^&*()-_+=";

    // Method for generating random password
    public static String randomPassword(){

        //Class for generate randndom bytes
        SecureRandom random = new SecureRandom();

        // Class for dynamic creating a string of characters
        StringBuilder stringBuilder = new StringBuilder();

        //Adding first uppercase random letter
        // Generate random bytes number 0-25 and match last number (26) to appropriate random letter from CHARACTERS string and uppercase this letter
        stringBuilder.append((char) (random.nextInt(26) + 'A'));

        //Adding next 6 random letters
        for (int i = 0; i < 6; i++) {
            // Generate random byte number on CHARACTERS string lenght, and maching to appropriate random letter from CHARACTERS string to the generated byte
            stringBuilder.append(CHARACTERS.charAt(random.nextInt(CHARACTERS.length())));
        }

        // Adding special character that will be last letter in password
        // Generate random byte number on SPECIAL_CHARACTER lenght, and matching to appriopriatae random special character from SPECIAL_CHARACTERS to the generated byte
        stringBuilder.append(SPECIAL_CHARACTERS.charAt(random.nextInt(SPECIAL_CHARACTERS.length())));

        return stringBuilder.toString();
    }

}
